language: python

python:
  - "3.6"
  - "3.7-dev"

install:
  - pip install pipenv codecov
  - pipenv install --dev
  - pipenv run pip install -e .

script: pipenv run py.test --cov

after_success:
  - codecov
